import { useEffect, useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import { useAuth } from '../context/AuthContext'
import { dataApi } from '../services/dataApi'

type Department = { id: string; name: string; head: string; parentDepartment?: string; employees: number; status: 'Active' | 'Inactive' }
type Category = { code: string; name: string; custodian: string; warrantyPeriod?: string; status: 'Active' | 'Inactive'; assets?: number }
type Employee = { employee_id: string; name: string; email: string; department: string; role: 'employee' | 'department_head' | 'asset_manager'; status: 'Active' | 'Inactive' }
type SetupTab = 'departments' | 'categories' | 'employees'
type Editing = Department | Category | Employee | null

const roleLabel = (role: string) => role === 'department_head' ? 'Department Head' : role === 'asset_manager' ? 'Asset Manager' : 'Employee'
const labels: Record<SetupTab, string> = { departments: 'Department', categories: 'Category', employees: 'Employee' }

export function OrganizationSetup() {
  const { token, user } = useAuth()
  const [tab, setTab] = useState<SetupTab>('departments')
  const [departments, setDepartments] = useState<Department[]>([])
  const [categories, setCategories] = useState<Category[]>([])
  const [employees, setEmployees] = useState<Employee[]>([])
  const [query, setQuery] = useState('')
  const [notice, setNotice] = useState('')
  const [editing, setEditing] = useState<Editing>(null)
  const [modalOpen, setModalOpen] = useState(false)

  useEffect(() => { if (!token) return; Promise.all([dataApi.list<Department>('departments', token), dataApi.list<Category>('categories', token), dataApi.list<Employee>('employees', token)]).then(([departmentData, categoryData, employeeData]) => { setDepartments(departmentData.departments); setCategories(categoryData.categories); setEmployees(employeeData.employees.map((employee) => { const role = employee.role as string; return { ...employee, role: role === 'Department Head' ? 'department_head' : role === 'Asset Manager' ? 'asset_manager' : role as Employee['role'] } })) }).catch((reason) => setNotice(reason instanceof Error ? reason.message : 'Unable to load organization data.')) }, [token])
  if (user?.role !== 'admin') return <section className="organization-page"><header className="org-header"><div><h1>Organization Setup</h1><p>Only administrators can manage master data and role promotions.</p></div><div className="admin-pill">Admin access required</div></header></section>
  const rows = tab === 'departments' ? departments : tab === 'categories' ? categories : employees
  const filtered = useMemo(() => rows.filter((row) => Object.values(row).join(' ').toLowerCase().includes(query.toLowerCase())), [rows, query])
  const openNew = () => { setEditing(null); setModalOpen(true) }
  const save = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); if (!token) return
    const form = new FormData(event.currentTarget)
    try {
      if (tab === 'departments') {
        const name = String(form.get('name')).trim(), head = String(form.get('head')).trim(); if (!name || !head) return setNotice('Department name and head are required.')
        if (!editing && departments.some((item) => item.name.toLowerCase() === name.toLowerCase())) return setNotice('A department with this name already exists.')
        const record: Department = editing ? { ...(editing as Department), name, head, parentDepartment: String(form.get('parentDepartment')).trim() || undefined, employees: Number(form.get('employees')) || 0, status: String(form.get('status')) as Department['status'] } : { id: `D${String(departments.length + 1).padStart(3, '0')}`, name, head, parentDepartment: String(form.get('parentDepartment')).trim() || undefined, employees: Number(form.get('employees')) || 0, status: String(form.get('status')) as Department['status'] }
        await dataApi.save('departments', record, token); setDepartments((items) => editing ? items.map((item) => item.id === record.id ? record : item) : [...items, record])
      } else if (tab === 'categories') {
        const code = String(form.get('code')).trim().toUpperCase(), name = String(form.get('name')).trim(); if (!code || !name) return setNotice('Category code and name are required.')
        if (!editing && categories.some((item) => item.code === code)) return setNotice('A category with this code already exists.')
        const record: Category = { code, name, custodian: String(form.get('custodian')).trim(), warrantyPeriod: String(form.get('warrantyPeriod')).trim() || undefined, status: String(form.get('status')) as Category['status'], assets: (editing as Category | null)?.assets || 0 }
        await dataApi.save('categories', record, token); setCategories((items) => editing ? items.map((item) => item.code === record.code ? record : item) : [...items, record])
      } else {
        const employee_id = String(form.get('employee_id')).trim().toUpperCase(), name = String(form.get('name')).trim(), email = String(form.get('email')).trim(); if (!employee_id || !name || !/^\S+@\S+\.\S+$/.test(email)) return setNotice('Employee ID, name, and valid email are required.')
        if (!editing && employees.some((item) => item.employee_id === employee_id)) return setNotice('An employee with this ID already exists.')
        const record: Employee = { employee_id, name, email, department: String(form.get('department')).trim(), role: String(form.get('role')) as Employee['role'], status: String(form.get('status')) as Employee['status'] }
        await dataApi.save('employees', record, token); setEmployees((items) => editing ? items.map((item) => item.employee_id === record.employee_id ? record : item) : [...items, record])
      }
      setModalOpen(false); setNotice(`${labels[tab]} saved successfully.`)
    } catch (reason) { setNotice(reason instanceof Error ? reason.message : `Unable to save ${labels[tab].toLowerCase()}.`) }
  }
  const toggleStatus = async (row: Department | Category | Employee) => { if (!token) return; const record = { ...row, status: row.status === 'Active' ? 'Inactive' as const : 'Active' as const }; try { await dataApi.save(tab, record, token); if (tab === 'departments') setDepartments((items) => items.map((item) => item.id === (record as Department).id ? record as Department : item)); if (tab === 'categories') setCategories((items) => items.map((item) => item.code === (record as Category).code ? record as Category : item)); if (tab === 'employees') setEmployees((items) => items.map((item) => item.employee_id === (record as Employee).employee_id ? record as Employee : item)); setNotice(`${labels[tab]} ${record.status === 'Active' ? 'activated' : 'deactivated'}.`) } catch { setNotice('Unable to update status.') } }
  const deactivate = toggleStatus
  return <section className="organization-page"><header className="org-header"><div><h1>Organization Setup</h1><p>Admin-only master data for departments, categories, and employees.</p></div><div className="admin-pill">Admin only</div></header><div className="org-tabs">{(['departments', 'categories', 'employees'] as SetupTab[]).map((item) => <button key={item} className={tab === item ? 'selected' : ''} onClick={() => { setTab(item); setQuery('') }}>{item === 'departments' ? 'Departments' : item === 'categories' ? 'Asset Categories' : 'Employee Directory'}</button>)}</div><div className="org-toolbar"><p>{filtered.length} {tab}</p><div><label className="org-search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Search ${labels[tab].toLowerCase()}...`} /></label><button className="new-record" onClick={openNew}>+ New {labels[tab]}</button></div></div>{notice && <div className="org-notice">{notice}<button onClick={() => setNotice('')}>×</button></div>}
    <div className="org-table-wrap"><table className="org-table"><thead>{tab === 'departments' ? <tr><th>ID</th><th>Department</th><th>Head</th><th>Parent</th><th>Status</th><th>Actions</th></tr> : tab === 'categories' ? <tr><th>Code</th><th>Category</th><th>Custodian</th><th>Warranty</th><th>Status</th><th>Actions</th></tr> : <tr><th>Employee ID</th><th>Employee</th><th>Department</th><th>Role</th><th>Status</th><th>Actions</th></tr>}</thead><tbody>{(filtered as Array<Department | Category | Employee>).map((row) => tab === 'departments' ? <tr key={(row as Department).id}><td>{(row as Department).id}</td><td className="primary-cell">{(row as Department).name}</td><td>{(row as Department).head}</td><td>{(row as Department).parentDepartment || '—'}</td><td><span className={`status ${(row as Department).status.toLowerCase()}`}>{(row as Department).status}</span></td><td><button className="table-action" onClick={() => { setEditing(row); setModalOpen(true) }}>✎</button><button className="table-action" onClick={() => deactivate(row as Department)}>⊘</button></td></tr> : tab === 'categories' ? <tr key={(row as Category).code}><td>{(row as Category).code}</td><td className="primary-cell">{(row as Category).name}</td><td>{(row as Category).custodian || '—'}</td><td>{(row as Category).warrantyPeriod || '—'}</td><td><span className={`status ${(row as Category).status.toLowerCase()}`}>{(row as Category).status}</span></td><td><button className="table-action" onClick={() => { setEditing(row); setModalOpen(true) }}>✎</button><button className="table-action" onClick={() => deactivate(row as Category)}>⊘</button></td></tr> : <tr key={(row as Employee).employee_id}><td>{(row as Employee).employee_id}</td><td className="primary-cell">{(row as Employee).name}<small>{(row as Employee).email}</small></td><td>{(row as Employee).department}</td><td>{roleLabel((row as Employee).role)}</td><td><span className={`status ${(row as Employee).status.toLowerCase()}`}>{(row as Employee).status}</span></td><td><button className="table-action" onClick={() => { setEditing(row); setModalOpen(true) }}>✎</button><button className="table-action" onClick={() => deactivate(row as Employee)}>⊘</button></td></tr>)}</tbody></table></div>
    {modalOpen && <div className="setup-modal-backdrop"><form className="setup-modal" onSubmit={save}><div><h2>{editing ? `Edit ${labels[tab]}` : `New ${labels[tab]}`}</h2><button type="button" onClick={() => setModalOpen(false)}>×</button></div>{tab === 'departments' ? <><label>Name<input name="name" defaultValue={(editing as Department | null)?.name} required /></label><label>Department Head<input name="head" defaultValue={(editing as Department | null)?.head} required /></label><label>Parent Department<input name="parentDepartment" defaultValue={(editing as Department | null)?.parentDepartment} placeholder="Optional parent department" /></label><label>Employees<input name="employees" type="number" min="0" defaultValue={(editing as Department | null)?.employees || 0} /></label></> : tab === 'categories' ? <><label>Code<input name="code" defaultValue={(editing as Category | null)?.code} required /></label><label>Name<input name="name" defaultValue={(editing as Category | null)?.name} required /></label><label>Custodian<input name="custodian" defaultValue={(editing as Category | null)?.custodian} /></label><label>Warranty Period<input name="warrantyPeriod" defaultValue={(editing as Category | null)?.warrantyPeriod} placeholder="e.g. 36 months" /></label></> : <><label>Employee ID<input name="employee_id" defaultValue={(editing as Employee | null)?.employee_id} required /></label><label>Name<input name="name" defaultValue={(editing as Employee | null)?.name} required /></label><label>Email<input name="email" type="email" defaultValue={(editing as Employee | null)?.email} required /></label><label>Department<input name="department" defaultValue={(editing as Employee | null)?.department} required /></label><label>Role<select name="role" defaultValue={(editing as Employee | null)?.role || 'employee'}><option value="employee">Employee</option><option value="department_head">Department Head</option><option value="asset_manager">Asset Manager</option></select></label></>}<label>Status<select name="status" defaultValue={(editing as { status?: string } | null)?.status || 'Active'}><option>Active</option><option>Inactive</option></select></label><footer><button type="button" onClick={() => setModalOpen(false)}>Cancel</button><button className="new-record">Save {labels[tab]}</button></footer></form></div>}
  </section>
}
