import Database from 'better-sqlite3'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { mkdirSync } from 'node:fs'

const folder = join(dirname(fileURLToPath(import.meta.url)), 'data')
mkdirSync(folder, { recursive: true })
const db = new Database(join(folder, 'assetnexsus.db'))
db.pragma('journal_mode = WAL')
db.exec(`CREATE TABLE IF NOT EXISTS assets (tag TEXT PRIMARY KEY, data TEXT NOT NULL, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS departments (id TEXT PRIMARY KEY, data TEXT NOT NULL, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS categories (code TEXT PRIMARY KEY, data TEXT NOT NULL, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS employees (employee_id TEXT PRIMARY KEY, data TEXT NOT NULL, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS resources (id TEXT PRIMARY KEY, data TEXT NOT NULL, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS bookings (id TEXT PRIMARY KEY, data TEXT NOT NULL, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS dashboard (id INTEGER PRIMARY KEY CHECK (id = 1), data TEXT NOT NULL, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS allocations (id TEXT PRIMARY KEY, data TEXT NOT NULL, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS transfers (id TEXT PRIMARY KEY, data TEXT NOT NULL, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);`)
const seed = (table, key, rows) => { const insert = db.prepare(`INSERT OR IGNORE INTO ${table} (${key}, data) VALUES (?, ?)`); const transaction = db.transaction(() => rows.forEach((row) => insert.run(row[key], JSON.stringify(row)))); transaction() }
seed('assets', 'tag', [{tag:'AF-0001',name:'Dell XPS 15 Laptop',category:'Electronics',location:'IT Block — Floor 2',holder:'Arjun Mehta',department:'Information Technology',status:'Allocated',condition:'Excellent',serial:'DLL-XPS-2024-001',acquired:'2024-01-15',cost:'₹145,000'},{tag:'AF-0002',name:'MacBook Pro M3',category:'Electronics',location:'Marketing — Floor 3',holder:'Kavya Nair',department:'Marketing',status:'Allocated',condition:'Excellent',serial:'APL-M3-2024-032',acquired:'2024-02-10',cost:'₹178,000'},{tag:'AF-0003',name:'HP LaserJet Pro',category:'Electronics',location:'HR — Floor 1',holder:'Priya Sharma',department:'Human Resources',status:'Available',condition:'Good',serial:'HP-LJ-2023-119',acquired:'2023-08-22',cost:'₹32,500'},{tag:'AF-0004',name:'Toyota Innova Crysta',category:'Vehicles',location:'Ground Parking',holder:'Operations Pool',department:'Operations',status:'Allocated',condition:'Good',serial:'TYT-IC-2023-007',acquired:'2023-06-18',cost:'₹2,145,000'},{tag:'AF-0005',name:'Conference Room A — Projector',category:'Electronics',location:'Conference Room A',holder:'Facilities Team',department:'Facilities',status:'Available',condition:'Excellent',serial:'EP-PRO-2024-017',acquired:'2024-03-06',cost:'₹68,000'},{tag:'AF-0006',name:'Cisco Catalyst 9300 Switch',category:'IT Equipment',location:'Server Room — Floor 2',holder:'IT Infrastructure',department:'Information Technology',status:'Under Maintenance',condition:'Fair',serial:'CSC-9300-2022-015',acquired:'2022-11-08',cost:'₹92,000'}])
seed('departments', 'id', [{id:'D001',name:'Information Technology',head:'Arjun Mehta',employees:34,status:'Active'},{id:'D002',name:'Human Resources',head:'Priya Sharma',employees:12,status:'Active'},{id:'D003',name:'Finance',head:'Rohan Gupta',employees:18,status:'Active'},{id:'D004',name:'Operations',head:'Sneha Patel',employees:45,status:'Active'},{id:'D005',name:'Marketing',head:'Kavya Nair',employees:22,status:'Active'},{id:'D006',name:'Facilities',head:'Vikram Joshi',employees:8,status:'Active'},{id:'D007',name:'Research & Development',head:'Ananya Das',employees:0,status:'Inactive'}])
seed('categories', 'code', [{code:'CAT-IT',name:'IT Equipment',assets:148,custodian:'Information Technology',status:'Active'},{code:'CAT-OFF',name:'Office Furniture',assets:86,custodian:'Facilities',status:'Active'},{code:'CAT-VEH',name:'Vehicles',assets:14,custodian:'Operations',status:'Active'},{code:'CAT-SW',name:'Software Licenses',assets:67,custodian:'Information Technology',status:'Active'}])
seed('employees', 'employee_id', [{employee_id:'EMP-1001',name:'Arjun Mehta',department:'Information Technology',role:'Department Head',email:'arjun@assetnesus.com',status:'Active'},{employee_id:'EMP-1002',name:'Priya Sharma',department:'Human Resources',role:'Department Head',email:'priya@assetnesus.com',status:'Active'},{employee_id:'EMP-1003',name:'Rohan Gupta',department:'Finance',role:'Department Head',email:'rohan@assetnesus.com',status:'Active'},{employee_id:'EMP-1004',name:'Sneha Patel',department:'Operations',role:'Department Head',email:'sneha@assetnesus.com',status:'Active'}])
seed('resources', 'id', [{id:'meeting-b2',code:'AF-0008',name:'Meeting Room B2',area:'Block B · Floor 2',category:'Meeting Rooms',status:'Reserved'},{id:'projector-a',code:'AF-0005',name:'Conference Room A — Projector',area:'Conference Room A',category:'Electronics',status:'Available'},{id:'innova',code:'AF-0004',name:'Toyota Innova Crysta',area:'Ground Parking',category:'Vehicles',status:'Allocated'},{id:'oscilloscope',code:'AF-0012',name:'Oscilloscope — Rigol DS1054Z',area:'Lab Room 3',category:'Lab Equipment',status:'Available'}])
seed('bookings', 'id', [{id:'b1',resourceId:'meeting-b2',person:'Priya Sharma',department:'Human Resources',purpose:'Quarterly HR review',date:'2026-07-14',start:'09:00',end:'10:30',status:'Upcoming'},{id:'b2',resourceId:'meeting-b2',person:'Arjun Mehta',department:'Information Technology',purpose:'Infrastructure planning',date:'2026-07-14',start:'11:00',end:'12:30',status:'Upcoming'},{id:'b3',resourceId:'meeting-b2',person:'Aarav Shah',department:'Operations',purpose:'Vendor call',date:'2026-07-13',start:'15:00',end:'16:00',status:'Completed'},{id:'b4',resourceId:'innova',person:'Rahul Verma',department:'Operations',purpose:'Site visit — Andheri warehouse',date:'2026-07-12',start:'08:00',end:'14:00',status:'Ongoing'}])
export const listRows = (table) => db.prepare(`SELECT data FROM ${table} ORDER BY updated_at DESC`).all().map((row) => JSON.parse(row.data))
export const saveRow = (table, key, value) => db.prepare(`INSERT INTO ${table} (${key}, data, updated_at) VALUES (?, ?, CURRENT_TIMESTAMP) ON CONFLICT(${key}) DO UPDATE SET data = excluded.data, updated_at = CURRENT_TIMESTAMP`).run(value[key], JSON.stringify(value))
export const removeRow = (table, key, value) => db.prepare(`DELETE FROM ${table} WHERE ${key} = ?`).run(value)
export default db

seed('allocations', 'id', [
  { id: 'a1', assetTag: 'AF-0114', assetName: 'Dell XPS 15 Laptop', holder: 'Priya Sharma', holderType: 'Employee', department: 'Human Resources', allocatedOn: '2024-01-15', expectedReturnDate: '2025-01-15', status: 'Overdue', notes: 'Top cover scratch; needs battery check' },
  { id: 'a2', assetTag: 'AF-0002', assetName: 'MacBook Pro M3', holder: 'Kavya Nair', holderType: 'Employee', department: 'Marketing', allocatedOn: '2024-02-20', expectedReturnDate: '2025-02-20', status: 'Active' },
  { id: 'a3', assetTag: 'AF-0007', assetName: 'Standing Desk â€” Ergonomic', holder: 'Ananya Das', holderType: 'Employee', department: 'Information Technology', allocatedOn: '2024-01-30', expectedReturnDate: '2025-01-30', status: 'Active' },
  { id: 'a4', assetTag: 'AF-0011', assetName: 'iPad Pro 12.9"', holder: 'Rohan Gupta', holderType: 'Employee', department: 'Finance', allocatedOn: '2024-04-05', expectedReturnDate: '2025-04-05', status: 'Active' },
  { id: 'a5', assetTag: 'AF-0004', assetName: 'Toyota Innova Crysta', holder: 'Operations Pool', holderType: 'Department', department: 'Operations', allocatedOn: '2022-06-01', expectedReturnDate: '2025-06-01', status: 'Active' },
])
seed('transfers', 'id', [
  { id: 't1', assetTag: 'AF-0114', assetName: 'Dell XPS 15 Laptop', from: 'Priya Sharma', to: 'Raj Mehta', requestedBy: 'Raj Mehta', approvedBy: 'M. Shah', status: 'Re-allocated', history: ['Requested by Raj Mehta', 'Approved by Asset Manager', 'Re-allocated to Raj Mehta'] },
  { id: 't2', assetTag: 'AF-0002', assetName: 'MacBook Pro M3', from: 'Kavya Nair', to: 'Product Design', requestedBy: 'Kavya Nair', approvedBy: 'A. Verma', status: 'Approved', history: ['Requested by Kavya Nair', 'Approved by Department Head'] },
])
